spring.application.name=Ecommerce-website

# ===============================
# PostgresSQL Datasource
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerceDb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ankitdasgupta123@gmail.com
spring.mail.password=mlpw omlk rtlx cqml
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true